### ISSUE TITLE
projecting perpendicular vectors gives strange result

### ISSUE THREAD

**Issue by florisdesmedt** [undefx/vecpy#3]
when running:
```
w = Vec(10.0, 0.0)
v = Vec(0.0, 10.0)
w_proj_v = v.proj(w)
```
I would have expecting the resulting vector be zero in both orientations (`[0.0, 0.0, 0.0]`). The results however is
`[0.0, 1.0, 0.0]`

**Comment by undefx** [comment]
I'm a little lost -- vecpy is for SIMD vectorization, not vector math. Did you mean to post this on a different project?

**Comment by florisdesmedt** [comment]
The project/package I wanted to refer to is https://pypi.python.org/pypi/vecpy/0.1.1. Same name, different code it seems.

Best regards
